// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupExportPackage() {
  return window['go']['main']['App']['BackupExportPackage']();
}

export function BackupGetManifestTemplate() {
  return window['go']['main']['App']['BackupGetManifestTemplate']();
}

export function BackupGetScopeDefinition() {
  return window['go']['main']['App']['BackupGetScopeDefinition']();
}

export function BackupImportPackage(arg1) {
  return window['go']['main']['App']['BackupImportPackage'](arg1);
}

export function BackupInitializeSystem() {
  return window['go']['main']['App']['BackupInitializeSystem']();
}

export function BookmarkList() {
  return window['go']['main']['App']['BookmarkList']();
}

export function BookmarkReset() {
  return window['go']['main']['App']['BookmarkReset']();
}

export function BookmarkSave(arg1) {
  return window['go']['main']['App']['BookmarkSave'](arg1);
}

export function BookmarkSyncToProfiles() {
  return window['go']['main']['App']['BookmarkSyncToProfiles']();
}

export function BrowserClearCookies(arg1) {
  return window['go']['main']['App']['BrowserClearCookies'](arg1);
}

export function BrowserCoreDelete(arg1) {
  return window['go']['main']['App']['BrowserCoreDelete'](arg1);
}

export function BrowserCoreExtendedInfo() {
  return window['go']['main']['App']['BrowserCoreExtendedInfo']();
}

export function BrowserCoreList() {
  return window['go']['main']['App']['BrowserCoreList']();
}

export function BrowserCorePickDirectory() {
  return window['go']['main']['App']['BrowserCorePickDirectory']();
}

export function BrowserCoreSave(arg1) {
  return window['go']['main']['App']['BrowserCoreSave'](arg1);
}

export function BrowserCoreSetDefault(arg1) {
  return window['go']['main']['App']['BrowserCoreSetDefault'](arg1);
}

export function BrowserCoreValidate(arg1) {
  return window['go']['main']['App']['BrowserCoreValidate'](arg1);
}

export function BrowserExportCookies(arg1) {
  return window['go']['main']['App']['BrowserExportCookies'](arg1);
}

export function BrowserExtensionDelete(arg1) {
  return window['go']['main']['App']['BrowserExtensionDelete'](arg1);
}

export function BrowserExtensionInstall(arg1) {
  return window['go']['main']['App']['BrowserExtensionInstall'](arg1);
}

export function BrowserExtensionInstallLocalFile() {
  return window['go']['main']['App']['BrowserExtensionInstallLocalFile']();
}

export function BrowserExtensionInstallWithProxy(arg1) {
  return window['go']['main']['App']['BrowserExtensionInstallWithProxy'](arg1);
}

export function BrowserExtensionList() {
  return window['go']['main']['App']['BrowserExtensionList']();
}

export function BrowserExtensionLookup(arg1) {
  return window['go']['main']['App']['BrowserExtensionLookup'](arg1);
}

export function BrowserExtensionLookupWithProxy(arg1) {
  return window['go']['main']['App']['BrowserExtensionLookupWithProxy'](arg1);
}

export function BrowserExtensionSetEnabled(arg1, arg2) {
  return window['go']['main']['App']['BrowserExtensionSetEnabled'](arg1, arg2);
}

export function BrowserGetAllTags() {
  return window['go']['main']['App']['BrowserGetAllTags']();
}

export function BrowserGetCookies(arg1) {
  return window['go']['main']['App']['BrowserGetCookies'](arg1);
}

export function BrowserInstanceGetTabs(arg1) {
  return window['go']['main']['App']['BrowserInstanceGetTabs'](arg1);
}

export function BrowserInstanceOpenUrl(arg1, arg2) {
  return window['go']['main']['App']['BrowserInstanceOpenUrl'](arg1, arg2);
}

export function BrowserInstanceRestart(arg1) {
  return window['go']['main']['App']['BrowserInstanceRestart'](arg1);
}

export function BrowserInstanceStart(arg1) {
  return window['go']['main']['App']['BrowserInstanceStart'](arg1);
}

export function BrowserInstanceStartByCode(arg1) {
  return window['go']['main']['App']['BrowserInstanceStartByCode'](arg1);
}

export function BrowserInstanceStartDirect(arg1) {
  return window['go']['main']['App']['BrowserInstanceStartDirect'](arg1);
}

export function BrowserInstanceStartWithParams(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowserInstanceStartWithParams'](arg1, arg2, arg3, arg4);
}

export function BrowserInstanceStatus(arg1) {
  return window['go']['main']['App']['BrowserInstanceStatus'](arg1);
}

export function BrowserInstanceStop(arg1) {
  return window['go']['main']['App']['BrowserInstanceStop'](arg1);
}

export function BrowserProfileBatchRemoveTags(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileBatchRemoveTags'](arg1, arg2);
}

export function BrowserProfileBatchSetTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserProfileBatchSetTags'](arg1, arg2, arg3);
}

export function BrowserProfileCopy(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileCopy'](arg1, arg2);
}

export function BrowserProfileCopyWithMode(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserProfileCopyWithMode'](arg1, arg2, arg3);
}

export function BrowserProfileCopyWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserProfileCopyWithOptions'](arg1, arg2, arg3);
}

export function BrowserProfileCreate(arg1) {
  return window['go']['main']['App']['BrowserProfileCreate'](arg1);
}

export function BrowserProfileDelete(arg1) {
  return window['go']['main']['App']['BrowserProfileDelete'](arg1);
}

export function BrowserProfileExtensionGet(arg1) {
  return window['go']['main']['App']['BrowserProfileExtensionGet'](arg1);
}

export function BrowserProfileExtensionSave(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserProfileExtensionSave'](arg1, arg2, arg3);
}

export function BrowserProfileGetCode(arg1) {
  return window['go']['main']['App']['BrowserProfileGetCode'](arg1);
}

export function BrowserProfileList() {
  return window['go']['main']['App']['BrowserProfileList']();
}

export function BrowserProfileListByTag(arg1) {
  return window['go']['main']['App']['BrowserProfileListByTag'](arg1);
}

export function BrowserProfilePackageExport(arg1) {
  return window['go']['main']['App']['BrowserProfilePackageExport'](arg1);
}

export function BrowserProfilePackageImport() {
  return window['go']['main']['App']['BrowserProfilePackageImport']();
}

export function BrowserProfilePermanentlyDelete(arg1) {
  return window['go']['main']['App']['BrowserProfilePermanentlyDelete'](arg1);
}

export function BrowserProfileRegenerateCode(arg1) {
  return window['go']['main']['App']['BrowserProfileRegenerateCode'](arg1);
}

export function BrowserProfileRestore(arg1) {
  return window['go']['main']['App']['BrowserProfileRestore'](arg1);
}

export function BrowserProfileSetCode(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetCode'](arg1, arg2);
}

export function BrowserProfileSetKeywords(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetKeywords'](arg1, arg2);
}

export function BrowserProfileTrashCleanup() {
  return window['go']['main']['App']['BrowserProfileTrashCleanup']();
}

export function BrowserProfileTrashList() {
  return window['go']['main']['App']['BrowserProfileTrashList']();
}

export function BrowserProfileUpdate(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileUpdate'](arg1, arg2);
}

export function BrowserProxyBatchCheckIPHealth(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchCheckIPHealth'](arg1, arg2);
}

export function BrowserProxyBatchTestSpeed(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchTestSpeed'](arg1, arg2);
}



export function BrowserProxyCheckIPHealth(arg1) {
  return window['go']['main']['App']['BrowserProxyCheckIPHealth'](arg1);
}







export function BrowserProxyList() {
  return window['go']['main']['App']['BrowserProxyList']();
}


export function BrowserProxyListGroups() {
  return window['go']['main']['App']['BrowserProxyListGroups']();
}


export function BrowserProxyResolveLocation(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyResolveLocation'](arg1, arg2);
}

export function BrowserProxyTestSpeed(arg1) {
  return window['go']['main']['App']['BrowserProxyTestSpeed'](arg1);
}



export function BrowserRenameTag(arg1, arg2) {
  return window['go']['main']['App']['BrowserRenameTag'](arg1, arg2);
}

export function BrowserSnapshotCreate(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotCreate'](arg1, arg2);
}

export function BrowserSnapshotDelete(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotDelete'](arg1, arg2);
}

export function BrowserSnapshotList(arg1) {
  return window['go']['main']['App']['BrowserSnapshotList'](arg1);
}

export function BrowserSnapshotRestore(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotRestore'](arg1, arg2);
}

export function ClearAppLogs() {
  return window['go']['main']['App']['ClearAppLogs']();
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function FrontendOperationLog(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['FrontendOperationLog'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function GetBrowserSettings() {
  return window['go']['main']['App']['GetBrowserSettings']();
}

export function GetInterceptor() {
  return window['go']['main']['App']['GetInterceptor']();
}

export function GetLaunchServerInfo() {
  return window['go']['main']['App']['GetLaunchServerInfo']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetProxyCheckSettings() {
  return window['go']['main']['App']['GetProxyCheckSettings']();
}

export function GetRunningInstances() {
  return window['go']['main']['App']['GetRunningInstances']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function MoveInstancesToGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveInstancesToGroup'](arg1, arg2);
}

export function OpenCorePath(arg1) {
  return window['go']['main']['App']['OpenCorePath'](arg1);
}

export function OpenProjectRoot() {
  return window['go']['main']['App']['OpenProjectRoot']();
}

export function OpenUserDataDir(arg1) {
  return window['go']['main']['App']['OpenUserDataDir'](arg1);
}

export function QuitAppOnly() {
  return window['go']['main']['App']['QuitAppOnly']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SaveBrowserProxies(arg1) {
  return window['go']['main']['App']['SaveBrowserProxies'](arg1);
}

export function SaveBrowserSettings(arg1) {
  return window['go']['main']['App']['SaveBrowserSettings'](arg1);
}

export function SaveProxyCheckSettings(arg1) {
  return window['go']['main']['App']['SaveProxyCheckSettings'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StartInstanceWithParams(arg1, arg2) {
  return window['go']['main']['App']['StartInstanceWithParams'](arg1, arg2);
}

export function StatusInstance(arg1) {
  return window['go']['main']['App']['StatusInstance'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}

export function TestProxyConnectivity(arg1, arg2) {
  return window['go']['main']['App']['TestProxyConnectivity'](arg1, arg2);
}


export function TriggerGC() {
  return window['go']['main']['App']['TriggerGC']();
}

export function UpdateGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2);
}

export function ValidateProxyConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateProxyConfig'](arg1, arg2);
}

export function WaitInstanceDebugReady(arg1, arg2, arg3) {
  return window['go']['main']['App']['WaitInstanceDebugReady'](arg1, arg2, arg3);
}
