// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {backup} from '../models';
import {config} from '../models';
import {browser} from '../models';
import {proxy} from '../models';
import {logger} from '../models';
import {launchcode} from '../models';
import {time} from '../models';

export function BackupExportPackage():Promise<Record<string, any>>;

export function BackupGetManifestTemplate():Promise<backup.Manifest>;

export function BackupGetScopeDefinition():Promise<backup.Scope>;

export function BackupImportPackage(arg1:boolean):Promise<Record<string, any>>;

export function BackupInitializeSystem():Promise<Record<string, any>>;

export function BookmarkList():Promise<Array<config.BrowserBookmark>>;

export function BookmarkReset():Promise<void>;

export function BookmarkSave(arg1:Array<config.BrowserBookmark>):Promise<void>;

export function BookmarkSyncToProfiles():Promise<backend.BookmarkSyncResult>;

export function BrowserClearCookies(arg1:string):Promise<void>;

export function BrowserCoreDelete(arg1:string):Promise<void>;

export function BrowserCoreExtendedInfo():Promise<Array<browser.CoreExtendedInfo>>;

export function BrowserCoreList():Promise<Array<config.BrowserCore>>;

export function BrowserCorePickDirectory():Promise<backend.BrowserCorePickResult>;

export function BrowserCoreSave(arg1:browser.CoreInput):Promise<void>;

export function BrowserCoreSetDefault(arg1:string):Promise<void>;

export function BrowserCoreValidate(arg1:string):Promise<browser.CoreValidateResult>;

export function BrowserExportCookies(arg1:string):Promise<string>;

export function BrowserExtensionDelete(arg1:string):Promise<void>;

export function BrowserExtensionInstall(arg1:string):Promise<browser.Extension>;

export function BrowserExtensionInstallLocalFile():Promise<browser.Extension>;

export function BrowserExtensionInstallWithProxy(arg1:backend.BrowserExtensionWebStoreRequest):Promise<browser.Extension>;

export function BrowserExtensionList():Promise<Array<browser.Extension>>;

export function BrowserExtensionLookup(arg1:string):Promise<browser.ExtensionLookupResult>;

export function BrowserExtensionLookupWithProxy(arg1:backend.BrowserExtensionWebStoreRequest):Promise<browser.ExtensionLookupResult>;

export function BrowserExtensionSetEnabled(arg1:string,arg2:boolean):Promise<browser.Extension>;

export function BrowserGetAllTags():Promise<Array<string>>;

export function BrowserGetCookies(arg1:string):Promise<Array<backend.CookieInfo>>;

export function BrowserInstanceGetTabs(arg1:string):Promise<Array<browser.Tab>>;

export function BrowserInstanceOpenUrl(arg1:string,arg2:string):Promise<boolean>;

export function BrowserInstanceRestart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartByCode(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartDirect(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartWithParams(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<browser.Profile>;

export function BrowserInstanceStatus(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStop(arg1:string):Promise<browser.Profile>;

export function BrowserProfileBatchRemoveTags(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function BrowserProfileBatchSetTags(arg1:Array<string>,arg2:Array<string>,arg3:boolean):Promise<void>;

export function BrowserProfileCopy(arg1:string,arg2:string):Promise<browser.Profile>;

export function BrowserProfileCopyWithMode(arg1:string,arg2:string,arg3:string):Promise<browser.Profile>;

export function BrowserProfileCopyWithOptions(arg1:string,arg2:string,arg3:browser.ProfileCopyOptions):Promise<browser.Profile>;

export function BrowserProfileCreate(arg1:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProfileDelete(arg1:string):Promise<void>;

export function BrowserProfileExtensionGet(arg1:string):Promise<browser.ProfileExtensionSettings>;

export function BrowserProfileExtensionSave(arg1:string,arg2:Array<string>,arg3:boolean):Promise<browser.ProfileExtensionSettings>;

export function BrowserProfileGetCode(arg1:string):Promise<string>;

export function BrowserProfileList():Promise<Array<browser.Profile>>;

export function BrowserProfileListByTag(arg1:string):Promise<Array<browser.Profile>>;

export function BrowserProfilePackageExport(arg1:Array<string>):Promise<backend.ProfilePackageExportResult>;

export function BrowserProfilePackageImport():Promise<backend.ProfilePackageImportResult>;

export function BrowserProfilePermanentlyDelete(arg1:string):Promise<void>;

export function BrowserProfileRegenerateCode(arg1:string):Promise<string>;

export function BrowserProfileRestore(arg1:string):Promise<browser.Profile>;

export function BrowserProfileSetCode(arg1:string,arg2:string):Promise<string>;

export function BrowserProfileSetKeywords(arg1:string,arg2:Array<string>):Promise<browser.Profile>;

export function BrowserProfileTrashCleanup():Promise<void>;

export function BrowserProfileTrashList():Promise<Array<browser.Profile>>;

export function BrowserProfileUpdate(arg1:string,arg2:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProxyBatchCheckIPHealth(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyIPHealthResult>>;

export function BrowserProxyBatchTestSpeed(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyTestResult>>;


export function BrowserProxyBuildDiagnostic(arg1:string,arg2:string):Promise<proxy.ProxyBuildDiagnostic>;

export function BrowserProxyCheckIPHealth(arg1:string):Promise<backend.ProxyIPHealthResult>;







export function BrowserProxyList():Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListByGroup(arg1:string):Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListGroups():Promise<Array<string>>;

export function BrowserProxyProbeBrowserPage(arg1:backend.ProxyBrowserProbeRequest):Promise<backend.ProxyBrowserProbeResult>;

export function BrowserProxyResolveLocation(arg1:string):Promise<backend.ProxyLocationResolveResult>;

export function BrowserProxyTestSpeed(arg1:string):Promise<backend.ProxyTestResult>;



export function BrowserRenameTag(arg1:string,arg2:string):Promise<void>;

export function BrowserSnapshotCreate(arg1:string,arg2:string):Promise<backend.SnapshotInfo>;

export function BrowserSnapshotDelete(arg1:string,arg2:string):Promise<void>;

export function BrowserSnapshotList(arg1:string):Promise<Array<backend.SnapshotInfo>>;

export function BrowserSnapshotRestore(arg1:string,arg2:string):Promise<void>;

export function ClearAppLogs():Promise<void>;

export function CreateGroup(arg1:browser.GroupInput):Promise<browser.Group>;

export function DeleteGroup(arg1:string):Promise<void>;

export function ForceQuit():Promise<void>;

export function FrontendOperationLog(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:string):Promise<void>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetAppLogs():Promise<Array<logger.MemoryLogEntry>>;

export function GetBrowserSettings():Promise<browser.Settings>;

export function GetInterceptor():Promise<logger.MethodInterceptor>;

export function GetLaunchServerInfo():Promise<Record<string, any>>;

export function GetLogLevel():Promise<string>;

export function GetMemoryStats():Promise<Record<string, any>>;

export function GetProxyCheckSettings():Promise<config.ProxyCheckConfig>;

export function GetRunningInstances():Promise<Array<browser.Profile>>;

export function ListGroups():Promise<Array<browser.GroupWithCount>>;

export function MoveInstancesToGroup(arg1:Array<string>,arg2:string):Promise<void>;

export function OpenCorePath(arg1:string):Promise<void>;

export function OpenProjectRoot():Promise<void>;

export function OpenUserDataDir(arg1:string):Promise<void>;

export function QuitAppOnly():Promise<void>;

export function ReloadConfig():Promise<void>;

export function SaveBrowserProxies(arg1:Array<config.BrowserProxy>):Promise<void>;

export function SaveBrowserSettings(arg1:browser.Settings):Promise<void>;

export function SaveProxyCheckSettings(arg1:config.ProxyCheckConfig):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function StartInstance(arg1:string):Promise<browser.Profile>;

export function StartInstanceWithParams(arg1:string,arg2:launchcode.LaunchRequestParams):Promise<browser.Profile>;

export function StatusInstance(arg1:string):Promise<browser.Profile>;

export function StopInstance(arg1:string):Promise<browser.Profile>;

export function TestProxyConnectivity(arg1:string,arg2:string):Promise<backend.ProxyTestResult>;

export function TestProxyRealConnectivity(arg1:string):Promise<backend.ProxyTestResult>;

export function TriggerGC():Promise<void>;

export function UpdateGroup(arg1:string,arg2:browser.GroupInput):Promise<browser.Group>;

export function ValidateProxyConfig(arg1:string,arg2:string):Promise<backend.ProxyValidationResult>;

export function WaitInstanceDebugReady(arg1:string,arg2:number,arg3:time.Duration):Promise<browser.Profile>;
