export { TagManagementPage } from './TagManagementPage'
export { BrowserListPage } from './BrowserListPage'
export { BrowserDetailPage } from './BrowserDetailPage'
export { BrowserEditPage } from './BrowserEditPage'
export { BrowserCopyPage } from './BrowserCopyPage'

export { BrowserLogsPage } from './BrowserLogsPage'
export { ProxyPoolPage } from './ProxyPoolPage'
export { CoreManagementPage } from './CoreManagementPage'
export { BookmarkSettingsPage } from './BookmarkSettingsPage'
